config/routes.rb
Rails.application.routes.draw do

  root 'posts#index'

  resources :posts do
    member do
      put :like, to: 'posts#like'
      get :user_like, to: 'posts#user_like'
    end
    resources :comments, module: :posts
  end

  resources :comments do
    resources :comments, module: :comments
  end

  devise_for :users, controllers: { registrations: 'users/registrations',
                                    sessions: 'users/sessions' }
  resources :users, only: :show, as: :account
end

app/models/comment.rb
class Comment < ApplicationRecord
  include ActionView::RecordIdentifier
  include ActionView::Helpers::TextHelper

  belongs_to :user
  belongs_to :commentable, polymorphic: true, counter_cache: true
  belongs_to :parent, optional: true, class_name: 'Comment'
  has_many :comments, foreign_key: :parent_id, dependent: :destroy
  has_rich_text :body

  MAX_NESTING_DEPTH = 3

  validates :body, presence: true

  after_create_commit do
    broadcast_append_to [commentable, :comments], target: "#{dom_id(parent || commentable)}_comments", partial: "comments/comment_with_replies"
    update_comments_counter
    update_post_comments_data
  end

  after_update_commit do
    broadcast_replace_to self
  end

  after_destroy_commit do
    broadcast_remove_to self
    broadcast_action_to self, action: :remove, target: "#{dom_id(self)}_with_comments"
    update_comments_counter
    update_post_comments_data
  end

  def set_nesting
    if self.parent.present? && self.parent.nesting.present?
      self.nesting = self.parent.nesting + 1
    else
      self.nesting = 1
    end
  end

  def self.max_nesting
    MAX_NESTING_DEPTH
  end

  private

  def update_comments_counter
    broadcast_update_to [commentable, :comments], target: "#{dom_id(commentable)}_comments_counter",
                        html: "#{pluralize(commentable.comments.size, 'Comment').split().reverse.join(': ')}"
  end

  def update_post_comments_data
    post = self.commentable
    broadcast_update_to 'posts', target: "#{post.id}_comments_info", partial: 'posts/data_comments', locals: { post: post }
    broadcast_update_to commentable, target: "#{post.id}_comments_info", partial: 'posts/data_comments', locals: { post: post }
  end
end

app/controllers/comments/comments_controller.rb
class Comments::CommentsController  < ApplicationController
  include Commentable

  before_action :set_commentable

private

  def set_commentable
    @parent = Comment.find(params[:comment_id])
    @commentable = @parent.commentable
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_comment

  def show; end

  def edit
    render status: 403 unless @comment.user == current_user
  end

  def update
    render status: 403 unless @comment.user == current_user

    if @comment.update(comment_params)
      flash.now[:notice] = "Comment '#{@comment.id}' updated!"
      redirect_to @comment
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    render status: 403 unless @comment.user == current_user

    @comment.destroy
    flash.now[:notice] = "Comment '#{@comment.id}' destroyed!"
    respond_to do |format|
      format.turbo_stream
      format.html { redirect_to @comment.commentable }
    end
  end

  private

  def set_comment
    @comment = Comment.find(params[:id])
  end

  def comment_params
    params.require(:comment).permit(:body, :parent_id)
  end
end

app/controllers/posts/comments_controller.rb
class Posts::CommentsController  < ApplicationController
  include Commentable

  before_action :set_commentable

private

  def set_commentable
    @commentable = Post.find(params[:post_id])
  end
end

app/views/comments/_comment.html.erb
<%= turbo_stream_from comment %>
<%= turbo_frame_tag comment do %>
  <div class="pl-4 py-2 my-2 rounded-lg bg-gray-700">
    <div class="mx-4 mt-3 text-lg text-gray-200">
      <%= comment.body %>
    </div>
    <div class="mt-3 mb-1 pl-2 pr-4 flex justify-between items-center">
      <div class='text-xs mx-2 text-gray-400'>
        <%= time_ago_in_words(comment.created_at) %> ago by <%= comment.user&.email %>
      </div>
      <div class="flex items-center hidden"
           data-controller="object-author"
           data-object-author-author-id-value="<%= comment.user.id %>">
          <%= link_to edit_comment_path(comment),
                      class: 'mr-2 text-yellow-400 opacity-50 hover:text-yellow-500 text-md hover:opacity-100' do %>
            <svg xmlns="http://www.w3.org/2000/svg" class="h-5 w-5" viewBox="0 0 20 20" fill="currentColor">
              <path d="M13.586 3.586a2 2 0 112.828 2.828l-.793.793-2.828-2.828.793-.793zM11.379 5.793L3 14.172V17h2.828l8.38-8.379-2.83-2.828z" />
            </svg>
          <% end %>
          <%= button_to comment_path(comment), method: :delete,
                      data: { confirm: 'Are you sure?'},
                      class: 'mr-2 text-yellow-400 opacity-50 hover:text-yellow-500 text-md hover:opacity-100' do %>
            <svg xmlns="http://www.w3.org/2000/svg" class="h-5 w-5 mt-1" fill="none" viewBox="0 0 24 24" stroke="currentColor">
              <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M19 7l-.867 12.142A2 2 0 0116.138 21H7.862a2 2 0 01-1.995-1.858L5 7m5 4v6m4-6v6m1-10V4a1 1 0 00-1-1h-4a1 1 0 00-1 1v3M4 7h16" />
            </svg>
          <% end %>
        <%# end %>
      </div>
    </div>
  </div>
<% end %>

app/views/comments/_comment_with_replies.html.erb
<%= turbo_stream_from comment, :comments %>

<div class="pl-4 ml-4 border-gray-600"
     id="<%= dom_id(comment) %>_with_comments"
     data-controller="comment-reply "
     data-user-id="<%= comment.user.id %>">
  <%= render comment %>

  <div class="text-xs">
    <%= link_to "Reply", "javascript:void(0);", data: { action: "click->comment-reply#toggle" } %>

  </div>

  <div class="" id="<%= dom_id(comment) %>_comments">
    <%= render partial: "comments/form", locals: { commentable: comment, comment: Comment.new, data: { comment_reply_target: "form" }, class: "hidden" } %>
    <%= render partial: "comments/comment_with_replies", collection: comment.comments, as: :comment %>
  </div>
</div>

app/views/comments/_form.html.erb
<% model = [local_assigns[:commentable], comment].compact %>

<%= form_with model: model,
      id: dom_id_for_records(*model),
      data: local_assigns[:data],
      class: ["my-4"] + Array.wrap(local_assigns[:class]) do |form| %>

  <!-- errors -->
  <%= render 'shared/errors_form', form: form %>
  <!-- forms content -->
  <%= form.rich_text_area :body, rows: 4,
                  id: "#{dom_id_for_records(*model)}_body",
                  class: "block shadow rounded-md border border-gray-300 outline-none px-3 py-2 mt-2 w-full placeholder-gray-300 bg-transparent" %>
  <div class="mt-3 mb-5">
    <%= form.submit "#{form.object.new_record? ? 'Add comment' : 'Edit comment'}",
                  class: "rounded-lg py-2 px-4 mr-1 bg-yellow-400 filter saturate-150 contrast-75 text-yellow-800 font-medium hover:opacity-80 cursor-pointer" %>
    <% if form.object.persisted? %>
      <%= link_to 'Cancel', comment,
                    class: "py-2 px-4 bg-transparent border-2 border-gray-300 text-gray-300 text-lg filter saturate-150 contrast-75 opacity-50 rounded-lg hover:border-yellow-400 hover:text-yellow-400 hover:opacity-100 focus:border-4 focus:border-yellow-300 focus:opacity-90 transition duration-300 cursor-pointer"%>
    <% elsif form.object.errors.any? %>
      <%= link_to 'Cancel', "javascript:void(0);", data: { controller: 'comment-reply', action: "click->comment-reply#cancel", form_id: "#{dom_id_for_records(*model)}" },
                                class: "py-2 px-4 bg-transparent border-2 border-gray-300 text-gray-300 text-lg filter saturate-150 contrast-75 opacity-50 rounded-lg hover:border-yellow-400 hover:text-yellow-400 hover:opacity-100 focus:border-4 focus:border-yellow-300 focus:opacity-90 transition duration-300 cursor-pointer"%>
    <% end %>
  </div>
<% end %>

app/views/comments/create.turbo_stream.erb
<%#= # Return handled by cable %>

app/views/comments/edit.html.erb
<%= turbo_frame_tag @comment do %>
  <%= render 'form', comment: @comment %>
<% end %>

app/views/comments/show.html.erb
<%= turbo_frame_tag @comment do %>
  <%= render @comment %>
<% end %>