config/routes.rb
Rails.application.routes.draw do

  root 'posts#index'

  resources :posts do
    member do
      put :like, to: 'posts#like'
      get :user_like, to: 'posts#user_like'
    end
    resources :comments, module: :posts
  end

  resources :comments do
    resources :comments, module: :comments
  end

  devise_for :users, controllers: { registrations: 'users/registrations',
                                    sessions: 'users/sessions' }
  resources :users, only: :show, as: :account
end

app/views/shared/_down_direction.html.erb
<svg xmlns="http://www.w3.org/2000/svg" class="h-4 w-4" fill="none" viewBox="0 0 24 24" stroke="currentColor">
  <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M19 13l-7 7-7-7m14-8l-7 7-7-7" />
</svg>

app/views/shared/_dropdown_account.html.erb
<div class="inline-block text-sm px-4 py-2 leading-none rounded no-underline text-gray-300 bg-gray-800 hover:text-gray-400 hover:bg-gray-700 mt-4 lg:mt-0">
  <div class="relative"
       data-controller="dropdown"
       data-action='keyup@window->dropdown#closeWithKeyboard'>
    <div data-action="click->dropdown#toggle click@window->dropdown#hide"
         role="button"
         data-dropdown-target="button"
         tabindex="0"
         class="inline-block select-none outline-none">
      <span class="appearance-none flex items-center inline-block text-gray-700">
        <% if current_user %>
          <span class='h-9 w-9 align-middle mr-3 rounded-full ring-2 ring-gray-700'>
            <%= AvatarPresenter.call(current_user, 40)%>
          </span>
          <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 20 20" class="h-5 w-5 text-yellow-500" fill="currentColor">
            <path d="M9.293 12.95l.707.707L15.657 8l-1.414-1.414L10 10.828 5.757 6.586 4.343 8z"></path>
          </svg>
        <% end %>
      </span>
    </div>
    <div data-dropdown-target="menu" class="z-10 absolute -left-4 mt-2 bg-gray-800 hidden">
      <div class="bg-gray-800 shadow rounded border border-gray-600 overflow-hidden mt-1">
        <form>
          <div class="flex w-full bg-yellow-500 items-center px-4 py-2">
            <span class='italic my-1 text-yellow-800 font-medium mr-1'>
              <%= current_user&.email %>
            </span>
          </div>
          <%= link_to 'Profile',  account_path(current_user),
          data: { action: "click->dropdown#toggle", turbo_frame: 'user' },
          class: 'no-underline block pl-2 tracking-wider py-3 mt-1.5 mx-2 rounded text-gray-400 bg-gray-800 hover:bg-gray-600 hover:text-gray-300 whitespace-nowrap' %>
          <div class="h-px m-2 bg-gray-400"></div>
        </form>
        <%= button_to "Sign out", destroy_user_session_path, method: :delete,
            data: { action: "click->dropdown#toggle" },
            class: 'no-underline text-left w-full no-underline block pl-2 tracking-wider py-3 mt-1.5 mx-2 rounded text-gray-400 bg-gray-800 hover:bg-gray-600 hover:text-gray-300 whitespace-nowrap' %>
      </div>
    </div>
  </div>
</div>

app/views/shared/_errors.html.erb
<% if post.errors.any? %>
  <div id="error_explanation" class="bg-transparent border-l-8 border-red-500 py-3 px-5 text-red-500 font-medium rounded mt-3 mb-2 rounded-lg border-opacity-60">
    <h2><%= pluralize(post.errors.count, "error") %> prohibited this post from being saved:</h2>
    <ul class='mt-1'>
      <% post.errors.each do |error| %>
        <li>* <%= error.full_message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/shared/_errors_form.html.erb
<% if form.object.errors.any? %>
  <div id="error_explanation" class="bg-transparent border-l-8 border-red-500 py-3 px-5 text-red-500 font-medium rounded mt-3 mb-2 rounded-lg border-opacity-60">
    <h2><%= pluralize(form.object.errors.count, "error") %> prohibited this post from being saved:</h2>
    <ul class='mt-1'>
      <% form.object.errors.full_messages.each do |message| %>
        <li>* <%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/shared/_flash.html.erb
<div id="flash">
  <% flash.each do |type, message| %>
    <div class="fixed inset-x-0 top-0 flex items-end justify-right px-4 py-5 sm:p-5 justify-end z-30 pointer-events-none">
      <div
          data-controller="alert"
          data-alert-show-class="translate-x-0 opacity-100"
          data-alert-hide-class="translate-x-full opacity-0"
          class="max-w-sm w-full shadow-lg px-4 py-2 rounded relative bg-transparent border-l-8 border-yellow-500 text-white pointer-events-auto transition translate-x-full transform ease-in-out duration-1000 opacity-0">
        <div class="p-2">
          <div class="flex items-start">
            <div class="ml-3 w-0 flex-1 pt-0.5">
              <p class="text-sm leading-5 font-medium">
                <%= content_tag :div, message %>
              </p>
            </div>
            <div class="ml-4 flex-shrink-0 flex">
              <button data-action="alert#close" class="inline-flex text-white focus:outline-none focus:text-gray-300">
                <svg class="h-5 w-5" viewBox="0 0 20 20" fill="currentColor">
                  <path fill-rule="evenodd" d="M4.293 4.293a1 1 0 011.414 0L10 8.586l4.293-4.293a1 1 0 111.414 1.414L11.414 10l4.293 4.293a1 1 0 01-1.414 1.414L10 11.414l-4.293 4.293a1 1 0 01-1.414-1.414L8.586 10 4.293 5.707a1 1 0 010-1.414z" clip-rule="evenodd"/>
                </svg>
              </button>
            </div>
          </div>
        </div>
      </div>
    </div>
  <% end %>
</div>

app/views/shared/_footer.html.erb
<footer class="flex justify-center mt-12 px-4 text-gray-300 opacity-80 bg-gray-800 frame-loading-hide"
        data-endless-target="footer">
  <div class="container py-6">
    <h1 class="text-center text-lg font-bold lg:text-2xl">
      Join 31,000+ other and never miss <br> out on new tips, tutorials, and more.
    </h1>

    <div class="flex justify-center mt-6">
      <div class="bg-gray-600 rounded-lg">
        <div class="flex flex-wrap justify-between md:flex-row">
          <input type="email"
                 class="m-1 p-2 appearance-none text-gray-300 text-sm border-transparent rounded-lg outline-none focus:outline-none focus:ring-0 focus:border-yellow-600"
                 placeholder="Enter your email">
          <button class="w-full m-1 p-2 text-sm text-gray-400 bg-gray-900 opacity-80 rounded-lg transform hover:scale-95 hover:bg-gray-800 hover:opacity-100 duration-300 font-semibold uppercase lg:w-auto">
            subscribe
          </button>
        </div>
      </div>
    </div>

    <hr class="h-px mt-6 bg-gray-700 border-none">

    <div class="flex flex-col items-center justify-between mt-6 md:flex-row">
      <div>
          <a href="https://github.com/secretpray/Hotwire-CRUD-MODAL"
             class="text-xl font-bold transform hover:scale-110 duration-300 hover:text-yellow-500">
             Hotwire project
           </a>
      </div>
      <div class="flex mt-4 md:m-0">
        <div class="-mx-4">
          <a href="https://www.linkedin.com/in/александр-рубан-83b93578/" class="px-4 text-sm transform hover:scale-110 duration-300 hover:text-yellow-500">About</a>
          <a href="https://blog.corsego.com" class="px-4 text-sm transform hover:scale-110 duration-300 hover:text-yellow-500">Blog</a>
          <a href="https://github.com/secretpray?tab=repositories" class="px-4 text-sm transform hover:scale-110 duration-300 hover:text-yellow-500">News</a>
          <a href="https://github.com/secretpray" class="px-4 text-sm transform hover:scale-110 duration-300 hover:text-yellow-500">Contact</a>
      	</div>
      </div>
    </div>
  </div>
</footer>

app/views/shared/_header.html.erb
<head>
  <title>HotwireCrudModal</title>
  <meta name="viewport" content="width=device-width,initial-scale=1">
  <meta name="current-user-id" content="<%= current_user&.id %>">
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>
  <%= stylesheet_link_tag "inter-font", "data-turbo-track": "reload" %>
  <%= stylesheet_link_tag "tailwind", "data-turbo-track": "reload" %>
  <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
</head>

app/views/shared/_loader.html.erb
<span class="flex justify-center items-center frame-loading-show min-h-screen">
  <!-- Loading... -->
  <div class="loader">
    <div class="inner one"></div>
    <div class="inner two"></div>
    <div class="inner three"></div>
  </div>
</span>

app/views/shared/_page_next.html.erb
<% if page.next %>
  <%= link_to pagy_url_for(page, page.next), rel: "next",
              id: 'pagination-next',
              class: "mr-10 flex items-center rounded-full px-4 py-2 hover:border-yellow-500 hover:text-yellow-500 hover:opacity-100 border-2 opacity-30 hidden last-child:block",
              data: { endless_target: "pagination",
                      endless_request_value: "false",
                      disable_with: '&times;'
                    } do %>
    <span>
    </span>
    <span data-endless-target='next'
          data-service='<%= page.page %>' >
      <%= page.next %>
    </span>
  <% end %>
<% else %>
    <%= link_to ' ', 'javascript:void(0);',
                     class: "mr-10 w-11 h-11 flex items-center rounded-full px-4 py-2 hover:border-yellow-500 hover:text-yellow-500 hover:opacity-25 cursor-default border-2 opacity-30 hidden last-child:block",
                     disabled: true %>
<% end %>

app/views/shared/_page_prev.html.erb
<% if page.prev %>
  <%= link_to pagy_url_for(page, page.prev), rel: "prev",
              class: "ml-10 flex items-center rounded-full px-4 py-2 hover:border-yellow-500 hover:text-yellow-500 hover:opacity-100 border-2 opacity-30 hidden first-child:block",
              data: { endless_target: "pagination_prev",
                      disable_with: '&times;'} do %>
    <span class=''>
    </span>
    <span class=''>
      <%= page.prev %>
    </span>
  <% end %>
<% else %>
    <%= link_to ' '.html_safe,
                'javascript:void(0);',
                id: 'pagination-prev',
                class: "ml-10 flex w-11 h-11 items-center rounded-full px-4 py-2 hover:border-yellow-500 hover:text-yellow-500 hover:opacity-25 cursor-default border-2 opacity-30 hidden first-child:block",
                disabled: true %>
<% end %>

app/views/shared/_service.html.erb
<%= turbo_stream_from :user_history %>
<div class="flex flex-col">
  <div class="relative flex tooltip justify-end mr-10 active" id='header-tooltip'
        data-controller='hovercard'
        data-action="mouseover->hovercard#show mouseout->hovercard#hide">
    <%= link_to root_path,
        class: 'ml-10 mt-3 mb-3 px-2 pt-1 rounded text-left text-md text-gray-200 opacity-25 hover:opacity-75 transform duration-150',
        data: { turbo_frame: 'posts',
                action: 'click->service#hideHistory' } do %>
      <%= Time.zone.now.strftime("%A, %D: %k:%M:%S.%L") %>
    <% end %>
    <div class="flex flex-col px-3 py-1 bg-gray-800 text-gray-300 w-42 h-16 rounded-md z-20 absolute left-7 tooltip-item hidden"
      data-hovercard-target="card">
      <span class="font-semibold py-4">
        <%= link_to 'Home page', root_path,
            class: 'transform hover:bg-yellow-500 px-4 py-2 mr-5 text-gray-600 border-2 border-gray-600 rounded-lg hover:text-yellow-800 hover:border-yellow-500 duration-500',
            data: { turbo_frame: 'posts',
                    action: 'click->service#hideHistory' } %>
      </span>
    </div>
  </div>
  <div id='history'>
    <%= render partial: 'users/search_histories', locals: { histories: @histories} %>
  </div>
</div>

app/views/shared/_timer_loader.html.erb
<div id="loader"
     class="image-loader show my-4 flex justify-center items-center flex-col"
     data-endless-target='loader'>
  <!-- animation loader -->
  <svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" x="0px" y="0px"
       width='50px' height='55px' viewBox="0 0 30 30" fill="currentColor"
       class='text-gray-400' style="" xml:space="preserve">
    <rect x="0" y="13" width="4" height="5" >
      <animate attributeName="height" attributeType="XML"
        values="5;21;5"
        begin="0s" dur="0.6s" repeatCount="indefinite" />
      <animate attributeName="y" attributeType="XML"
        values="13; 5; 13"
        begin="0s" dur="0.6s" repeatCount="indefinite" />
    </rect>
    <rect x="10" y="13" width="4" height="5" >
      <animate attributeName="height" attributeType="XML"
        values="5;21;5"
        begin="0.15s" dur="0.6s" repeatCount="indefinite" />
      <animate attributeName="y" attributeType="XML"
        values="13; 5; 13"
        begin="0.15s" dur="0.6s" repeatCount="indefinite" />
    </rect>
    <rect x="20" y="13" width="4" height="5">
      <animate attributeName="height" attributeType="XML"
        values="5;21;5"
        begin="0.3s" dur="0.6s" repeatCount="indefinite" />
      <animate attributeName="y" attributeType="XML"
        values="13; 5; 13"
        begin="0.3s" dur="0.6s" repeatCount="indefinite" />
    </rect>
  </svg>
  <!-- Timer in sec and ms -->
  <p class='text-center text-secondary mt-1 text-xs' id='timer'>
    <span id="seconds" data-endless-target='seconds'>
    </span>.
    <span id="milliseconds" data-endless-target='milliseconds'>
    </span>
  </p>
</div>

app/views/shared/_up_direction.html.erb
<svg xmlns="http://www.w3.org/2000/svg" class="h-4 w-4" fill="none" viewBox="0 0 24 24" stroke="currentColor">
  <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M5 11l7-7 7 7M5 19l7-7 7 7" />
</svg>

app/views/shared/_user_auth.html.erb
<% if user_signed_in? %>
  <div class="flex items-center mr-2">
    <%= render 'shared/dropdown_account' %>

    <%= link_to 'New post', new_post_path,
    class: "p-2 ml-2 px-5 bg-transparent border-2 border-grey-300 text-grey-300 text-lg filter saturate-150 contrast-75 opacity-50 rounded-lg hover:border-yellow-400 hover:text-yellow-400 hover:opacity-100 focus:border-4 focus:border-yellow-300 focus:opacity-90 transition duration-300 cursor-pointer",
    data: { turbo_frame: :modal } %>
  </div>
<% else %>
  <ul>
    <div class="flex items-center mr-12">
      <li class="flex align-center">
        <%= link_to 'Sign up', new_user_registration_path,
            class: 'rounded-lg py-3 px-5 text-yellow-400 mr bg-transparent filter saturate-150 contrast-75 font-medium hover:underline' %>
      </li>
      <li class="flex align-center">
        <%= link_to 'Log in', new_user_session_path,
            data: { turbo: false },
            class: "p-2 ml-2 px-5 bg-transparent border-2 border-grey-300 text-grey-300 text-lg filter saturate-150 contrast-75 opacity-50 rounded-lg hover:border-yellow-400 hover:text-yellow-400 hover:opacity-100 focus:border-4 focus:border-yellow-300 focus:opacity-90 transition duration-300 cursor-pointer" %>
      </li>
    </div>
  </ul>
<% end %>