config/routes.rb
Rails.application.routes.draw do

  root 'posts#index'

  resources :posts do
    member do
      put :like, to: 'posts#like'
      get :user_like, to: 'posts#user_like'
    end
    resources :comments, module: :posts
  end

  resources :comments do
    resources :comments, module: :comments
  end

  devise_for :users, controllers: { registrations: 'users/registrations',
                                    sessions: 'users/sessions' }
  resources :users, only: :show, as: :account
end

app/models/post.rb
class Post < ApplicationRecord
  include ActionView::RecordIdentifier

  belongs_to :user, inverse_of: :posts
  has_many :comments, as: :commentable, dependent: :destroy
  has_many :likes, dependent: :destroy, inverse_of: :post
  has_rich_text :content

  enum status: %i[draft publish deleted spam]

  SORTED_METHODS      = %w(new old likes dislikes commentes uncommentes).freeze
  SORTED_TITLES       = ['By rating', 'By popularity', 'By date'].freeze
  COLOR_STATUSES      = { draft: 'grey', publish: 'orange', deleted: 'green', spam: 'red' }
  MIN_TITLE_LENGTH    = 4
  MAX_TITLE_LENGTH    = 120
  MIN_CONTENT_LENGTH  = 2

  validates :title, uniqueness: true
  validates :content, :status, presence: true
  validates :title, length: { in: MIN_TITLE_LENGTH..MAX_TITLE_LENGTH }
  validates :content, length: { minimum: MIN_CONTENT_LENGTH }
  validates :status, inclusion: { in: Post.statuses.keys }

  scope :with_title_category_containing, ->(query) { where("title ilike ? OR category ilike ?", "%#{query}%","%#{query}%") }
  scope :with_content_containing, ->(query) { joins(:rich_text_content).merge(ActionText::RichText.where('body ILIKE ?', "%#{query}%")) }
  scope :multi_records_containing_sanitize, -> (sanitize_query) { joins(:rich_text_content).merge(ActionText::RichText.where(sanitize_query)) }
  scope :multi_records_containing, -> (query) {
     joins(:rich_text_content).merge(ActionText::RichText.where('title ILIKE ? OR category ILIKE ? OR body ILIKE ?', "%#{query}%","%#{query}%","%#{query}%"))
  }
  scope :yesterday, -> { where('created_at < ? AND created_at > ?', Time.zone.now, Date.today.beginning_of_day) }
  scope :yesterday_deleted, -> { where(status: :deleted).where('created_at < ? AND created_at > ?', Time.zone.now, Date.today.beginning_of_day) }
  scope :last_week, -> { where('created_at < ? AND created_at > ?', Time.zone.now, Date.today.beginning_of_week) }
  scope :last_week_deleted, -> { where(status: :deleted).where('created_at < ? AND created_at > ?', Time.zone.now, Date.today.beginning_of_week) }
  scope :last_month, -> { where('created_at < ? AND created_at > ?', Time.zone.now, Date.today.beginning_of_month) }
  scope :last_month_deleted, -> { where(status: :deleted).where('created_at < ? AND created_at > ?', Time.zone.now, Date.today.beginning_of_month) }
  scope :commented, -> { order('comments_count') }
  scope :liked, -> { order('likes_count') }

  def self.sanitize_multi_search(query)
    sanitize_query = Post.sanitize_sql_for_conditions(['title ILIKE ? OR category ILIKE ? OR body ILIKE ?', "%#{query}%","%#{query}%","%#{query}%"])
    Post.multi_records_containing_sanitize(sanitize_query)
  end

  # Save sorted method
  def self.saved_sort
    @sort_list ||= Kredis.string "sort_list"
  end

  def self.get_saved_sort
    Post.saved_sort if @sort_list.nil?
    @sort_list.value
  end

  def self.set_saved_sort(sort_method)
    Post.saved_sort if @sort_list.nil?
    sort_method = sort_method.in?(SORTED_METHODS) ? sort_method : ''

    @sort_list.value = sort_method
  end

  def self.make_sort(selection, list)
    selection = selection.is_a?(Array) ? selection.join('') : selection

    case selection
    when 'new'
      Post.set_saved_sort('new')
      list.order(created_at: :desc)
    when 'old'
      Post.set_saved_sort('old')
      list.order(created_at: :asc)
    when 'likes'
      Post.set_saved_sort('likes')
      list.order(likes_count: :desc)
    when 'dislikes'
      Post.set_saved_sort('dislikes')
      list.order(likes_count: :asc)
    when 'commentes'
      Post.set_saved_sort('commentes')
      list.order(comments_count: :desc)
    when 'uncommentes'
      Post.set_saved_sort('uncommentes')
      list.order(comments_count: :asc)
    else
      list.recent
    end
  end

  # def self.parse_filter_params(params)
  #   case
  #   when !params[:filter_name].blank?
  #     @users = User.where('name ILIKE ? OR email ILIKE ?', "%#{params[:filter_name]}%", "%#{params[:filter_name]}%")
  #     # @users = result.includes(:team, :user)
  #     #               .where('name ILIKE ? OR description ILIKE ?', "%#{params[:filter_name]}%", "%#{params[:filter_name]}%")
  #   # when !params[:description].blank?
  #   #   @ingredients = Bio.joins(:action_text_rich_text)
  #   #                       .where("action_text_rich_texts.body ILIKE ?", "%#{params[:description]}%")
  #   #   @recipes = Recipe.joins(:ingredients).where("ingredients.id" => @ingredients)
  # when !params[:age].blank?
  #     @users = @users.where("age LIKE ?", "%#{params[:age]}%")
  #   else
  #     @users = @users.includes(:team)
  #   end
  # end

  def liked?(user)
    Like.where(post: self, user: user).any?
  end

  def update_like(user)
    if liked?(user)
      user.likes.find_by(post: self).destroy
    else
      user.likes.create(post_id: self.id)
    end
  end

  after_create_commit do
    broadcast_prepend_to 'posts', target: 'post_list',  partial: 'posts/post_brc', locals: { post: self, online_user_ids: User.online_users }
    update_posts_counter
  end

  after_update_commit do
    broadcast_replace_to self, partial: 'posts/post_brc', locals: { post: self, online_user_ids: User.online_users } # for broadcast with likes
  end

  after_destroy_commit do
    broadcast_remove_to self
    update_posts_counter
  end

  private

  def update_posts_counter
    broadcast_update_to 'posts', target: 'posts_counter', partial: 'posts/posts_counter', locals: { count: Post.count }
  end
end

app/controllers/posts/comments_controller.rb
class Posts::CommentsController  < ApplicationController
  include Commentable

  before_action :set_commentable

private

  def set_commentable
    @commentable = Post.find(params[:post_id])
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :authenticate_user!, except: %i[index show]
  before_action :set_post, only: [:show, :edit, :update, :destroy, :like, :user_like]
  before_action :auth_post, only: [:edit, :update, :destroy]
  before_action :get_online_user_id, only: %i[index show update]

  def index
    query = params[:query]
    current_user.recent_searches.prepend(query) unless query.blank?
    # make Search
    posts = query.blank? ? Post.all : Post.sanitize_multi_search(query)
    # make Sort
    if params[:sort].present?
      posts_unpaged = Post.make_sort(params[:sort], posts)
    else
      get_sort = Post.get_saved_sort
      posts_unpaged = get_sort.in?(Post::SORTED_METHODS) ? Post.make_sort(get_sort, posts) : posts.recent
    end
    # make Pagination
    @page, @posts = pagy(posts_unpaged, items: 10)
    # fetch saved sort params (from Redis DB)
    @sorted_value = Post.get_saved_sort
    # fetch saved searches User history (from Redis DB)
    @histories = current_user.recent_searches.elements
    # update user search list
    current_user.update_user_search_history(@histories) unless query.blank?
    # select method for render TURBO_STREAM (index.turbo_stream.erb)
    @endless_render = params[:endless].present?
    # remove blank params (if 'endless' = '')
    params.delete(:endless) if params[:endless].blank?
  end

  def show; end

  def new
    @post = Post.new
  end

  def edit; end

  def create
    @post = current_user.posts.build(post_params)

    flash.now[:notice] = "Post '#{@post.title}' created!" if @post.save
  end

  def update
    respond_to do |format|
      if @post.update(post_params)
        flash.now[:notice] = "Post '#{@post.title}' updated!"
        format.turbo_stream
      else
        format.turbo_stream
      end
    end
  end

  def destroy
    @post.destroy
    flash.now[:notice] = "Post '#{@post.title}' destroyed!"
    respond_to do |format|
      format.turbo_stream
    end
  end

  def like
    @post.update_like(current_user)
    flash.now[:notice] = "Thank you for rating!"

    respond_to do |format|
      format.turbo_stream { render turbo_stream: turbo_stream.update(:flash, partial: 'shared/flash') }
      format.html { redirect_to posts_url }
    end
  end

  def user_like
    respond_to do |format|
      format.turbo_stream
    end
  end

  private

  def set_post
    @post = Post.find(params[:id])
  end

  def post_params
    params.require(:post).permit(:title, :content, :status, :category, :user_id)
  end

  def auth_post
    render status: 403 unless @post.user == current_user
  end

  def get_online_user_id
    @online_user_ids = User.online_users
  end
end

app/helpers/posts_helper.rb
module PostsHelper

  def status_color(status)
    Post::COLOR_STATUSES[status.to_sym] || 'grey'
  end

  def truncated_title(title, controller_name, action_name)
    if controller_name == 'posts' && action_name == "show"
      title
    else
      truncate(title, length: 42, separator: ' ')
    end
  end

  def comments_user_data(post)
    comments_count = post.comments.count
    comment_users =  User.find(post.comments.pluck(:user_id).uniq)
    users_avatar = comment_users.map{|user| AvatarPresenter.call(user, 40)}

    return { count: comments_count, users_avatar: users_avatar.join(' ') }
  end

  def set_title(item)
    return unless item.downcase.in?(Post::SORTED_METHODS) || item.is_a?(String)

    if item.downcase.end_with?('likes')
      Post::SORTED_TITLES.first
    elsif item.downcase.end_with?('commentes')
      Post::SORTED_TITLES.second
    else
      Post::SORTED_TITLES.third
    end
  end

  def decode_sort_method(sorted_value)
    return 'none' unless sorted_value.in?(Post::SORTED_METHODS) || sorted_value.is_a?(String)

    direction =
      if sorted_value === 'new' || sorted_value === 'likes' || sorted_value === 'commentes'
        '&nbsp; <svg xmlns="http://www.w3.org/2000/svg" class="h-5 w-5 mt-1" fill="none" viewBox="0 0 24 24" stroke="currentColor">
          <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M15 13l-3 3m0 0l-3-3m3 3V8m0 13a9 9 0 110-18 9 9 0 010 18z" />
        </svg>'
      elsif sorted_value === 'old' || sorted_value === 'dislikes' || sorted_value === 'uncommentes'
        '&nbsp; <svg xmlns="http://www.w3.org/2000/svg" class="h-5 w-5 mt-1" fill="none" viewBox="0 0 24 24" stroke="currentColor">
          <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M9 11l3-3m0 0l3 3m-3-3v8m0-13a9 9 0 110 18 9 9 0 010-18z" />
        </svg>'
      end

    title = set_title(sorted_value).downcase
    title + direction
  end
end

app/views/posts/_data_comments.html.erb
<% data = comments_user_data(post) %>

<span class='flex w-full items-center'>
  <%= pluralize(data[:count], "Comment").split().reverse.join(': ') %>
  <% if data[:count] > 0 %>
    by&nbsp;
    <span class='flex w-4/6 ml-2 gap-1 truncate'>
      <%== data[:users_avatar] %>
    </span>
  <% end %>
</span>

app/views/posts/_form.html.erb
<% uniq_id = post.new_record? ? dom_id(post) : "form_#{dom_id(post)}" %>
<%= form_with( model: post, id: uniq_id,
               class: "contents",
               data: { turbo_frame_target: :_top } ) do |form| %>
  <div class="flex justify-between">
    <h1 class="font-bold text-4xl"><%= post.new_record? ? 'New post' : 'Edit post' %></h1>
    <a href="javascript:void(0);" class='text-orange-500 text-3xl font-semibold' data-action='modal#close'>&times;</a>
  </div>

  <%= render 'shared/errors', post: post %>

  <div class="my-5">
    <%= form.label :title %>
    <%= form.text_field :title, class: "block shadow rounded-md border border-gray-300 outline-none px-3 py-2 mt-2 w-full placeholder-gray-300 bg-transparent" %>
  </div>

  <div class="my5 flex gap-5">
    <div class="relative flex flex-1 flex-col pr-5">
      <div class="flex">
        Status:
        <%= form.select :status, options_for_select(Post.statuses.keys, { selected: @post&.status || Post.new.status }), {include_blank: false},
        { class: 'ml-4 appearance-none w-full border border-gray-300 hover:border-gray-500 rounded shadow leading-tight focus:outline-none focus:shadow-outline placeholder-gray-300 bg-transparent'} %>
      </div>
    </div>

    <div class="flex flex-1 flex-col">
      <div class="flex">
        Category:
        <%= form.text_field :category, class: "ml-4 w-full border border-gray-300 hover:border-gray-500 rounded shadow leading-tight focus:outline-none focus:shadow-outline placeholder-gray-300 bg-transparent" %>
      </div>
    </div>
  </div>

  <div class="my-5">
    <%= form.label :content %>
    <%= form.rich_text_area :content, rows: 4, class: "block shadow rounded-md border border-gray-300 outline-none px-3 py-2 mt-2 w-full placeholder-gray-300 bg-transparent" %>
  </div>

  <div class="ml-auto inline">
    <%= form.submit class: "rounded-lg py-3 px-5 bg-yellow-400 filter saturate-150 contrast-75 text-yellow-800 font-medium hover:opacity-80" %>
    <a href="javascript:void(0);" class='rounded-lg py-3 px-5 text-yellow-400 filter saturate-150 contrast-75 font-medium hover:underline' data-action='modal#close'>Cancel</a>
  </div>
<% end %>

app/views/posts/_likes_brc.html.erb
<%= button_to "Likes (#{post.likes.count})", like_post_path(post), method: 'put', disabled: true,
                    class: 'px-4 py-2 bg-transparent text-gray-400 border-2 rounded-xl border-gray-500 hover:border-gray-500 hover:text-gray-400 cursor-pointer',
                    data: { controller: 'likes', likes_target: 'button', likes_url_value: user_like_post_path(post), turbo_frame: 'posts' } %>

app/views/posts/_post.html.erb
<%= turbo_stream_from post, class: 'hidden' %>

<div id="<%= dom_id post %>"
     class=""
     loading="lazy">
  <div class='mx-4 p-4 post-card min-h-72 transform transition duration-500 hover:scale-95 group hover:bg-gray-700 cursor-pointer rounded-xl'
      data-controller='current-page'
      data-current-page-target='hover'
      data-action='dblclick->modal#showPost'
      data-id='<%= post.id %>'>
    <div class="mt-5 mb-1 mx-3 text-xl text-gray-200 truncate">
      <%= link_to post.title, post_path(post),
                  class: 'hover:text-yellow-400 focus:opacity-90 transition duration-300 cursor-pointer',
                  id: "btn_show_#{post.id}",
                  data: { modal_target: "showButton", turbo_frame: :_top } %>
    </div>
    <div class="flex justify-between">
      <div class='text-xs mx-3 self-center text-gray-400'>
        <!-- post.created_at.to_s(:short) -->
        <%= time_ago_in_words(post.created_at) %> ago by
        <span id='<%= dom_id(post) %>_user_email'>
          <%= render partial: 'users/user_email', locals: { post: post, online_user_ids: @online_user_ids } %>
        </span>
      </div>

      <div class="mr-2" id="<%= post.id %>_like">
        <%= render partial: 'posts/likes', locals: { post: post } %>
      </div>
    </div>
    <div class="flex justify-between">
      <p class="my-5 text-md flex-1 flex">
        <strong class="block font-semibold mb-1 mx-3 text-gray-400">
          Category:
        </strong>
        <%= post.category %>
      </p>

      <p class="my-5 text-xl w-full flex justify-end mr-2">
        <span class='text-xs px-3 py-2 text-center'
              style='border-left: 6px solid <%= status_color(post.status) %>;'>
          <%= post.status %>
        </span>
      </p>
    </div>

    <hr class='mx-3'>
    <div class="my-5 mx-3 text-xl">
      <span>
        <%= post.content %>
      </span>
    </div>

    <div class="mx-3 mt-3 mb-4 text-xs"
         id="<%= post.id %>_comments_info">
      <%= render partial: 'posts/data_comments', locals: { post: post } %>
    </div>

    <div class="mt-5 mb-3 pt-4 mx-3 flex items-center">
      <div class="flex items-center hidden"
           data-controller="object-author"
           data-object-author-author-id-value="<%= post.user.id %>">
        <%= link_to edit_post_path(post), data: { turbo_frame: :modal },
                            class: "mr-2 text-yellow-400 opacity-50 hover:text-yellow-500 text-md hover:opacity-100"  do %>
          <svg xmlns="http://www.w3.org/2000/svg" class="h-5 w-5" viewBox="0 0 20 20" fill="currentColor">
            <path d="M13.586 3.586a2 2 0 112.828 2.828l-.793.793-2.828-2.828.793-.793zM11.379 5.793L3 14.172V17h2.828l8.38-8.379-2.83-2.828z" />
          </svg>
        <% end %>
        <%= button_to post_path(post), method: :delete, data: { confirm: "Are you sure you want to delete this post?" },
                            class: "mr-2 text-yellow-400 opacity-50 hover:text-yellow-500 text-md hover:opacity-100" do %>
          <svg xmlns="http://www.w3.org/2000/svg" class="h-5 w-5 mt-1" fill="none" viewBox="0 0 24 24" stroke="currentColor">
            <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M19 7l-.867 12.142A2 2 0 0116.138 21H7.862a2 2 0 01-1.995-1.858L5 7m5 4v6m4-6v6m1-10V4a1 1 0 00-1-1h-4a1 1 0 00-1 1v3M4 7h16" />
          </svg>
        <% end %>
      </div>
      <div class="ml-auto back-button hidden"
           data-current-page-target='back_button'>
          <%= link_to '◄ Back', posts_path,
              data: { turbo_frame: :_top },
              class: "rounded-lg py-2 px-5 text-lg text-yellow-400 filter saturate-150 contrast-75 font-medium hover:underline hover:opacity-80 transition duration-300" %>
      </div>
    </div>
  </div>
</div>

app/views/posts/_posts_counter.html.erb
<div  class="popover inline-block"
      data-controller="popover"
      data-popover-translate-x="0"
      data-popover-translate-y="-128%"
      data-action="mouseover->popover#mouseOver mouseout->popover#mouseOut">
  <h1 class="text-lg font-bold text-4xl cursor-pointer">
    <%= pluralize(count, "Post").split().reverse.join(': ') %>
  </h1>
  <div class="content absolute max-w-xs text-gray-300 z-20 bg-gray-700 rounded-lg mt-2"
       data-popover-target="content"
       id='post-popover'>
    <div class="italic font-medium px-4 py-2 bg-yellow-500 text-yellow-800 rounded">
      Published (deleted) posts:
    </div>
    <div class="px-4 py-2 border-b-2 border-gray-500">
      <span>Yesterday:</span>
      <span class='float-right'>
        <span class='font-bold'><%= Post.yesterday.count %></span>
        (<span class='font-bold'><%= Post.yesterday_deleted.count %></span>);
      </span>
    </div>
    <div class="px-4 py-2 border-b-2 border-gray-500">
      <span>This week:</span>
      <span class='float-right'>
        <span class='font-bold'><%= Post.last_week.count %></span>
        (<span class='font-bold'><%= Post.last_week_deleted.count %></span>)
      </span>
    </div>
    <div class="px-4 py-2">
      <span>This month:</span>
      <span class='float-right'>
        <span class='font-bold'><%= Post.last_month.count %></span>
        (<span class='font-bold'><%= Post.last_month_deleted.count %></span>)
      </span>
    </div>
  </div>
</div>

app/views/posts/_reset_link.html.erb
<% if request.query_parameters[:query].present? %>
  <%= link_to 'reset', root_path,
      data: { turbo_frame: 'posts',
              action: 'click->service#hideHistory',
              request: request.query_parameters,
              posts_count: posts.count, all_count: Post.count },
      class: 'reset-search-link rounded-lg py-3 px-5 text-yellow-400 mr bg-transparent filter saturate-150 contrast-75 font-medium hover:underline' %>
<% end %>

app/views/posts/_select_form_item.html.erb
<div class="flex items-center" id='sort_by_<%=item%>'>
  <%= form.radio_button 'sort[]', item,
      class: 'sort-item appearance-none hidden',
      data: { action: "click->dropdown-sort#clickSort" },
      selected: sorted_value == item %>
  <label class="flex flex-col w-full cursor-pointer rounded-md <%= 'bg-yellow-500 text-yellow-900' if sorted_value == item %>" for="sort[]_<%= item %>">
    <div class='px-4 py-4 cursor-pointer flex items-center justify-between rounded whitespace-nowrap truncate uppercase font-semibold text-sm text-gray-500 hover:text-gray-300 hover:bg-gray-600 w-full'>
      <%= set_title(item) %>
      <% if index.odd? %>
        <%= render 'shared/down_direction' %>
      <% else %>
        <%= render 'shared/up_direction' %>
      <% end %>
    </div>
  </label>
</div>

app/views/posts/edit.html.erb
<%= turbo_frame_tag :modal do %>
  <div class="fixed flex flex-col items-center justify-center z-10 inset-0 overflow-y-auto w-full h-full bg-gray-900 bg-opacity-80"
     data-modal-target='container'
     data-action='click->modal#closeBackground keyup@window->modal#closeWithKeyboard'>
    <div class="bg-gray-800 rounded-lg max-w-3xl p-4">
      <div class="flex flex-col items-center overflow-hidden p-4">
        <div>
          <%= render "form", post: @post %>
        </div>
      </div>
    </div>
  </div>
<% end %>

app/views/posts/index.html.erb
<%= turbo_stream_from 'posts' %>

<%= turbo_frame_tag 'posts' do %>
  <% unless @posts.present? %>
    <div class="w-full flex justify-center pt-1">
      <div class="flex items-center w-full justify-between mt-10">
        <div class='flex items-center ml-12'>
          <h1 class="font-bold text-4xl text-gray-400 text-center w-full inline-block">
            No posts to display! Do you want to add?
          </h1>
        </div>
        <%= render 'shared/user_auth' %>
      </div>
    <div>
  <% else %>
    <div class="w-full mx-auto pt-1">
      <div class="mx-8 flex justify-between items-center mb-4">
        <div class='flex items-center'>
          <%= render 'select_form' %>
          <div id="posts_counter"
            <%= render 'posts/posts_counter', count: @page.count %>
          </div>
        </div>
        <%= render 'posts/search', posts: @posts %>
        <%= render 'shared/user_auth' %>
      </div>
      <% if @sorted_value.blank? %>
        <hr>
      <% else %>
        <span class='flex justify-between' data-controller="pagy">
          <div id='prev-page-link'>
            <%= render 'shared/page_prev', page: @page %>
          </div>
          <hr class='mt-5 flex-1 opacity-50'>
            <div class='flex items-center rounded-xl px-4 py-2 transform border-2 border-opacity-30 relative'
                 data-action="mouseover->pagy#mouseOver mouseout->pagy#mouseOut"
                 data-pagy-target="pagy"
                 id='page-wrapper'>
              <span class='flex transform opacity-30 hidden'
                    id='more-info'
                    data-pagy-target="more"
                    data-endless-target="current"
                    data-prevpage="<%= @page.page %>"
                    data-totalpage="<%= @page.pages %>"
                    data-prevpage-link-current="<%= pagy_url_for(@page, @page.page) %>">
                Page: <%= @page.page %> in <%= @page.pages %>
                <!-- (Posts: <%#= @page.offset + @page.in %> of <%#= @page.count %>) Page: 1 in 10 (Posts: 30 of 99) -->
                sorted <%== decode_sort_method(@sorted_value) %>
              </span>
              <span class='flex opacity-30 transform' id='lite-info' data-pagy-target="lite">
                <%== decode_sort_method(@sorted_value) %>
              </span>
            </div>
          <hr class='mt-5 flex-1 opacity-50'>
          <div id='next-page-link'>
            <%= render 'shared/page_next', page: @page %>
          </div>
        </span>
      <% end %>
    </div>
    <%= render 'shared/loader' %>
    <div class='grid gap-5 grid-cols-2 frame-loading-hide mt-8' id="post_list">
      <%= render @posts %>
      <div id="endless_list" class='hidden'></div>
    </div>
    <%= render 'shared/timer_loader' %>
  <% end %>
<% end %>

app/views/posts/index.turbo_stream.erb
<% if @endless_render %>
  <%# endless %>
  <%= turbo_stream.append('post_list', partial: 'posts/post', collection: @posts, as: :post, locals: { online_user_ids: User.online_users }, formats: [:html]) %>
  <%= turbo_stream.update('next-page-link', partial: 'shared/page_next', locals: { page: @page }, formats: [:html]) %>
<% else %>
  <%# standard_stream%>
  <%= turbo_stream.replace('post_list', partial: 'posts/post', collection: @posts, as: :post, locals: { online_user_ids: User.online_users }, formats: [:html]) %>
  <%= turbo_stream.update('prev-page-link', partial: 'shared/page_prev', locals: { page: @page }, formats: [:html]) %>
  <%= turbo_stream.update('next-page-link', partial: 'shared/page_next', locals: { page: @page }, formats: [:html]) %>
<% end %>

app/views/posts/like.turbo_stream.erb
<% # Return handled by cable %>

app/views/posts/new.html.erb
<%= turbo_frame_tag :modal do %>
  <div class="flex flex-col items-center justify-center fixed left-0 bottom-0 w-full h-full bg-gray-900 bg-opacity-80"
     data-modal-target='container'
     data-action='click->modal#closeBackground keyup@window->modal#closeWithKeyboard'>
    <div class="bg-gray-800 rounded-lg max-w-3xl p-4">
      <div class="flex flex-col items-center p-4">
        <div>
          <%= render "form", post: @post %>
        </div>
      </div>
    </div>
  </div>
<% end %>

app/views/posts/update.turbo_stream.erb
<% if @post.errors.any? %>
  <%= turbo_stream.replace "form_post_#{@post.id}", partial: 'posts/form', locals: { post: @post }, status: :unprocessable_entity %>
<% else %>
  <%= render_flash %>
  <%= turbo_stream.replace "post_#{@post.id}", partial: 'posts/post', locals: { post: @post, online_user_ids: @online_user_ids } %>
  <%= turbo_stream.update(:modal, nil) %>
<% end %>

app/views/posts/user_like.turbo_stream.erb
<%= turbo_stream.update("#{@post.id}_like", partial: 'posts/likes', locals: { post: @post}) %>